### ISSUE TITLE
Did you support providing a model as a decorator of a method ?

### ISSUE THREAD

**Issue by chermed** [mardix/assembly#12]
A simple question, if I suggest a PR for something like below ... will have a chance to be accepted ? or it complicate the development ?
```

from assembly import models, view_model, view_filter, view_order, view_model_options

class Blog(Assembly):

    @view_model(models.Article)
    @view_filter("published == true")
    @view_order("published_date desc")
    @view_model_options(per_page=10)
    def index(self):
        pass

```
this code should send a recordset of 10 articles to the view after gathering and applying the other arguments like current page, order, merging with user query and other filters.

**Comment by mardix** [comment]
It would be an interesting addition, but I would like to see more use cases for this. 

However, going with this, with having the query be done explicitly in the index method, than having many decorators. 

```
class Blog(Assembly):
  
    def index(self):
        results = models.Article.query()
          .filter(models.Article.published == True)
          .order_by(models.Article.published_date.desc())
          .paginate(per_page=10)
          
        return results
```


1- Decorators overload. One method could be having 
2- response ? What kind of response would we have. 
3- Error handling. If the Error is coming from the decorator itself, it would be harder to debug
4- 
```
    @view_filter("published == true")
    @view_order("published_date desc")
```
While I don't mind reinventing the wheel, SQLAlchemy already provided such functionalities in a python manner.


But I do like where this is going though.

**Comment by chermed** [comment]
The purpose of my proposal is to complete the case when a view (template) is automatically rendered based on the name of the method, I wanted that I add a Model to be handled by the jinja expression.

so when I type : 

```
@view_model(Article)
def index(self):
    pass
```

should render a list of article when we visit `/blog`.

In your case of :

```
class Blog(Assembly):
  
    def index(self):
        results = models.Article.query()
          .filter(models.Article.published == True)
          .order_by(models.Article.published_date.desc())
          .paginate(per_page=10)
          
        return results

```
the return should be `return render_template('blog/index.html', {'results': results))` because the return for me is a rendered page.

You can close this issue, I will try to find another way if I can propose something more simple !

**Comment by mardix** [comment]
No problem my friend.  Great ideas btw and Happy New Year!
