### ISSUE TITLE
Long term support

### ISSUE THREAD

**Issue by laith43d** [mardix/assembly#7]
Hi,

I've been using Flask for a long time.

My question: Is this a serious project? I mean is there a plan for long term stable support, if so I'm very likely to use it in my coming project as I began to like it :) 

Thanks

**Comment by mardix** [comment]
It is a serious project. I'm intended and it is intended to have long term support. 

I'm using it in some personal projects, also in some enterprise applications. 

The interest for Assembly is here, the community is responding positively, as it progresses I'm expecting more support to come. 

Thanks for your interest.
